# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: (C) 2022 nfitzen <https://github.com/nfitzen<

version: 0.1.0
author: "nfitzen"
name: "NLIB"
description: "Basic stuff (not guaranteed) to make your life easier."

data_pack:
    load: ["src", "libs/load"]
    pack_format: 10
    description: "Basic stuff (not guaranteed) to make your life easier.\n\
                  /function nlib:copyright for copr. info."
    render:
        functions:
            - "nlib*:*"

require:
    - mecha.contrib.nesting
    - mecha.contrib.relative_location

pipeline:
    - mecha
    - beet.contrib.installation_advancement
    - beet.contrib.copy_files
    - beet_nlib.gen_set_size

output: "out"

meta:
    copy_files:
        data_pack:
            ".":
                - "README.md"
                - "LICENSE"
                - "LICENSES/"

    mecha:
        multiline: true

    installation_advancement:
        author_skull_owner: "FitzenN"

    uuid:
        nlib:
            worldborder_center:
                hex: "ad7a10d4-7d3c-4f43-86bb-da872d12bb79"
                data: "[I;-1384509228,2101104451,-2034509177,756202361]"
